
language: python
matrix:
  include:   
      - { python: '2.7', env: }
      - { arch: arm64, python: '2.7', env: }
      - { python: '3.4', env: }
      - { arch: arm64, python: '3.4', env: }
      - { python: '3.5', env: }
      - { arch: arm64, python: '3.5', env: }
      - { python: '3.6', env: }
      - { arch: arm64, python: '3.6', env: }
      - { python: '3.7-dev', env: }
      - { arch: arm64, python: '3.7-dev', env: }
install:
    - pip install --upgrade pip
    - pip install coverage
    - pip install --upgrade pytest pytest-benchmark

script:
    - |
      if [[ $(bc <<< "$TRAVIS_PYTHON_VERSION >= 3.3") -eq 1 ]]; then
         py.test --doctest-modules multipledispatch
      else
         py.test --doctest-modules --ignore=multipledispatch/tests/test_dispatcher_3only.py multipledispatch
      fi

after_success:
    - |
      if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls; coveralls ; fi

notifications:
  email: false
